name: BlockRegen
main: nl.Aurorion.BlockRegen.Main
version: 3.4.0
author: [Aurorion]
softdepend: [Vault, WorldEdit, Towny, Jobs, GriefPrevention]
api-version: 1.13

commands:
  blockregen:
    aliases: [br]